version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mediavault-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
    networks:
      - mediavault

  minio:
    image: minio/minio:latest
    container_name: mediavault-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - mediavault

volumes:
  mongodb_data:
  minio_data:

networks:
  mediavault:
    driver: bridge